configuration:
  sinks: [0, 1, 2, 3]
  sources:
    0: {upstream_conv: 0}
    1: {upstream_conv: 1}
  conveyors:
    0:
      length: 40
      upstream: {type: 'sink', idx: 0}
    1:
      length: 30
      upstream: {type: 'conveyor', idx: 5, pos: 10}
    2:
      length: 20
      upstream: {type: 'conveyor', idx: 3, pos: 0}
    3:
      length: 30
      upstream: {type: 'conveyor', idx: 4, pos: 0}
    4:
      length: 20
      upstream: {type: 'sink', idx: 0}
    5:
      length: 43
      upstream: {type: 'sink', idx: 3}
    6:
      length: 10
      upstream: {type: 'conveyor', idx: 0, pos: 20}
    7:
      length: 10
      upstream: {type: 'conveyor', idx: 2, pos: 10}
    8:
      length: 3
      upstream: {type: 'sink', idx: 1}
    9:
      length: 3
      upstream: {type: 'sink', idx: 1}
    10:
      length: 3
      upstream: {type: 'sink', idx: 2}
    11:
      length: 3
      upstream: {type: 'sink', idx: 2}
    12:
      length: 3
      upstream: {type: 'sink', idx: 3}
  diverters:
    0:
      conveyor: 0
      pos: 10
      upstream_conv: 2
    1:
      conveyor: 0
      pos: 30
      upstream_conv: 5
    2:
      conveyor: 1
      pos: 10
      upstream_conv: 7
    3:
      conveyor: 1
      pos: 20
      upstream_conv: 6
    4:
      conveyor: 3
      pos: 10
      upstream_conv: 12
    5:
      conveyor: 3
      pos: 20
      upstream_conv: 11
    6:
      conveyor: 4
      pos: 10
      upstream_conv: 9
    7:
      conveyor: 5
      pos: 20
      upstream_conv: 8
    8:
      conveyor: 5
      pos: 30
      upstream_conv: 10

settings:
  bags_distr:
    sequence:
      # - {bags_number: 200, delta: 20, sinks: [0, 1]}
      # - {bags_number: 200, delta: 20}
      # - {bags_number: 200, delta: 20, sinks: [0, 1]} 
      # - {bags_number: 200, delta: 20}
      # - {bags_number: 200, delta: 20, simult_sources: 2} 
      # - {bags_number: 400, delta: 10, simult_sources: 2}
      # - {bags_number: 600, delta: 7, simult_sources: 2}
      
      - {bags_number: 200, delta: 10}
      - {bags_number: 200, delta: 7}
      - {bags_number: 200, delta: 5}
      - {bags_number: 200, delta: 3}
      - {bags_number: 200, delta: 1.5}

      # - {bags_number: 800, delta: 4, simult_sources: 2}
      # - {bags_number: 1100, delta: 3, simult_sources: 2}
      # - {bags_number: 1200, delta: 2.5, simult_sources: 2}
      # - {bags_number: 800, delta: 2, simult_sources: 2}
      # - {bags_number: 666, delta: 4}
      # - {bags_number: 430, delta: 3}
  conveyor_env:
    speed: 1
    energy_consumption: 1
  conveyor:
    stop_delay: 40
  router:
    simple_q:
      energy_reward_weight: 0.3
      learning_rate: 0.5
    dqn: &dqn
      energy_reward_weight: 1
      # energy_reward_weight: 0.8
      optimizer: 'rmsprop'
      scope: 'conveyor_test_ng'
      activation: 'relu'
      layers: [64, 64]
      additional_inputs:
        - tag: 'amatrix'
      batch_size: 1
      mem_capacity: 1
    dqn_oneout:
      <<: *dqn
    dqn_emb:
      <<: *dqn
      # energy_reward_weight: 0.2
      energy_reward_weight: 0.5
      additional_inputs: []
      # additional_inputs:
        # - tag: 'working'
          # dim: 1
      embedding:
        alg: 'lap'
        dim: 10

