network:
  - {u: 0, v: 1, latency: 10, bandwidth: 1024}
  - {u: 0, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 6, latency: 10, bandwidth: 1024}
  - {u: 2, v: 6, latency: 10, bandwidth: 1024}
  - {u: 1, v: 8, latency: 10, bandwidth: 1024}
  - {u: 8, v: 9, latency: 10, bandwidth: 1024}
  - {u: 6, v: 7, latency: 10, bandwidth: 1024}
  - {u: 3, v: 4, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 3, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 9, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    seed: 42
    sequence:
      - {pkg_number: 65000, delta: 10}
  synchronizer:
    period: 100
    delta: 10
  logging:
    delta: 200
  router:
    learning_rate: 0.2
    pkg_process_delay: 5
    model_file: null
    batch_size: 1
    mem_capacity: 1
    prioritized_xp: False
 
