network:
  - {u: 0, v: 1, latency: 10, bandwidth: 1024}
  - {u: 1, v: 2, latency: 10, bandwidth: 1024}
  - {u: 0, v: 3, latency: 10, bandwidth: 1024}
  - {u: 1, v: 4, latency: 10, bandwidth: 1024}
  - {u: 2, v: 5, latency: 10, bandwidth: 1024}
  - {u: 3, v: 4, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 3, v: 6, latency: 10, bandwidth: 1024}
  - {u: 4, v: 7, latency: 10, bandwidth: 1024}
  - {u: 5, v: 8, latency: 10, bandwidth: 1024}
  - {u: 6, v: 7, latency: 10, bandwidth: 1024}
  - {u: 7, v: 8, latency: 10, bandwidth: 1024}
  - {u: 6, v: 9, latency: 10, bandwidth: 1024}
  - {u: 7, v: 10, latency: 10, bandwidth: 1024}
  - {u: 8, v: 11, latency: 10, bandwidth: 1024}
  - {u: 9, v: 10, latency: 10, bandwidth: 1024}
  - {u: 10, v: 11, latency: 10, bandwidth: 1024}
  - {u: 9, v: 12, latency: 10, bandwidth: 1024}
  - {u: 10, v: 13, latency: 10, bandwidth: 1024}
  - {u: 11, v: 14, latency: 10, bandwidth: 1024}
  - {u: 13, v: 14, latency: 10, bandwidth: 1024}
  - {u: 12, v: 15, latency: 10, bandwidth: 1024}
  - {u: 15, v: 16, latency: 10, bandwidth: 1024}
  - {u: 16, v: 17, latency: 10, bandwidth: 1024}
  - {u: 11, v: 27, latency: 10, bandwidth: 1024}
  - {u: 17, v: 33, latency: 10, bandwidth: 1024}
  - {u: 18, v: 19, latency: 10, bandwidth: 1024}
  - {u: 19, v: 20, latency: 10, bandwidth: 1024}
  - {u: 18, v: 21, latency: 10, bandwidth: 1024}
  - {u: 19, v: 22, latency: 10, bandwidth: 1024}
  - {u: 20, v: 23, latency: 10, bandwidth: 1024}
  - {u: 21, v: 22, latency: 10, bandwidth: 1024}
  - {u: 22, v: 23, latency: 10, bandwidth: 1024}
  - {u: 21, v: 24, latency: 10, bandwidth: 1024}
  - {u: 22, v: 25, latency: 10, bandwidth: 1024}
  - {u: 23, v: 26, latency: 10, bandwidth: 1024}
  - {u: 24, v: 25, latency: 10, bandwidth: 1024}
  - {u: 25, v: 26, latency: 10, bandwidth: 1024}
  - {u: 24, v: 27, latency: 10, bandwidth: 1024}
  - {u: 25, v: 28, latency: 10, bandwidth: 1024}
  - {u: 26, v: 29, latency: 10, bandwidth: 1024}
  - {u: 27, v: 28, latency: 10, bandwidth: 1024}
  - {u: 28, v: 29, latency: 10, bandwidth: 1024}
  - {u: 27, v: 30, latency: 10, bandwidth: 1024}
  - {u: 28, v: 31, latency: 10, bandwidth: 1024}
  - {u: 29, v: 32, latency: 10, bandwidth: 1024}
  - {u: 30, v: 31, latency: 10, bandwidth: 1024}
  - {u: 32, v: 35, latency: 10, bandwidth: 1024}
  - {u: 33, v: 34, latency: 10, bandwidth: 1024}
  - {u: 34, v: 35, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    seed: 44
    sequence:
      # - {pkg_number: 1000, delta: 10} 
      - {pkg_number: 100, delta: 10}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {pkg_number: 1500, delta: 3.5, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
      - {pkg_number: 500, delta: 10, sources: [0, 1, 2, 6], dests: [3, 4, 5, 7]}
  synchronizer:
    period:
      dqn: 500
      link_state: 200
      simple_q: 200
    delta: 10
  logging:
    delta: 500
  router:
    learning_rate: 0.5
    beta_rate: 0.7
    gamma_rate: 0.9
    pkg_process_delay: 5
    nn_type: 'ff_amatrix'
    optimizer: 'rmsprop'
    layers: [64, 64]
    batch_size: 1
    mem_capacity: 1
    prioritized_xp: False
 
