network:
  - {u: 0, v: 1, latency: 10, bandwidth: 1024}
  - {u: 0, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 2, latency: 10, bandwidth: 1024}
  - {u: 1, v: 3, latency: 10, bandwidth: 1024}
  - {u: 1, v: 4, latency: 10, bandwidth: 1024}
  - {u: 2, v: 3, latency: 10, bandwidth: 1024}
  - {u: 2, v: 4, latency: 10, bandwidth: 1024}
  - {u: 3, v: 4, latency: 10, bandwidth: 1024}
  - {u: 3, v: 5, latency: 10, bandwidth: 1024}
  - {u: 4, v: 5, latency: 10, bandwidth: 1024}
  - {u: 1, v: 6, latency: 10, bandwidth: 1024}
  - {u: 2, v: 6, latency: 10, bandwidth: 1024}
  - {u: 2, v: 8, latency: 10, bandwidth: 1024}
  - {u: 2, v: 9, latency: 10, bandwidth: 1024}
  - {u: 4, v: 7, latency: 10, bandwidth: 1024}
  - {u: 3, v: 7, latency: 10, bandwidth: 1024}
  - {u: 4, v: 10, latency: 10, bandwidth: 1024}
  - {u: 10, v: 9, latency: 10, bandwidth: 1024}
  - {u: 4, v: 9, latency: 10, bandwidth: 1024}

settings:
  pkg_distr:
    - {pkg_number: 500, delta: 20, sources: [7, 1, 9], dests: [8, 6, 11]}
  synchronizer:
    period: 20
    delta: 5
  logging:
    delta: 20
  router:
    learning_rate: 0.2
    pkg_process_delay: 3
